create table date_responses (
    id bigint generated by default as identity primary key,
    answer text,
    food text,
    vibe text,
    place text,
    date_choice text,
    created_at timestamp with time zone default now()
);

alter table date_responses enable row level security;

create policy "Allow anyone to submit a response"
on date_responses
for insert
to anon
with check (true);
